### ISSUE TITLE
need to format code blocks

### ISSUE THREAD

**Issue by bradnoble** [rocketinsights/edb_docs_advocacy#12]
right now it's just pre/code but no color

**Comment by epbarger** [comment]
I might have the change the style approach on the <code> blocks, because there is a different in classes between a <code> block in a <pre>, and a plain <code> block. I'm not sure if our MDX processor will be able to apply different classes depending on context. Otherwise this all looks good :+1:

**Comment by matt-edb** [comment]
Yeah whatever you recommend!

**Comment by matt-edb** [comment]
Actually, ignore the note about `$green-dark` text. Turns out I can just set the code color in the Bootstrap SASS theme file. :)
@nring
