### ISSUE TITLE
add katacoda embed(s) to advo docs

### ISSUE THREAD

**Issue by bradnoble** [rocketinsights/edb_docs_advocacy#13]
We need to get this in by Wed pm / Th am, latest, so we can test it before the demo on Fri

**Comment by josh-heyer** [comment]
Bit tight on space: https://edb-docs-adv-josh-skele-suffgu.herokuapp.com/getting-started/connecting_to_postgres/python/02_django
Gonna see what I can do about that in the AM - might be able to use a different layout.

**Comment by bradnoble** [comment]
@matt-edb @cero-miedo take a look at the space issue that katacoda embeds present. Ideas? Something like a sidenav toggle? Or we could pop katacoda embeds in a modal over the page?

**Comment by matt-edb** [comment]
Let's try a modal. I'll mock up in the wireframe.

**Comment by epbarger** [comment]
Alternatively, we could simply change the bootstrap container size from 1140 to 1380 (or similar)? Stripe doc's main content area is 1080 pixels, ours is currently ~840 (with some interior padding too). Personally I think this would be preferable. It also helps with the reduced content width we have when the table of contents is present. Thoughts?

**Comment by bradnoble** [comment]
@epbarger @matt-edb I like that idea, Evan. Matt, thoughts?

**Comment by matt-edb** [comment]
Awesome, let's do it!

**Comment by matt-edb** [comment]
I was working up a modal approach, but that's way better.

**Comment by josh-heyer** [comment]
Calling this done via https://github.com/rocketinsights/edb_docs/pull/70 and https://github.com/rocketinsights/edb_docs/pull/67 - but we'll likely keep tweaking. Also some things I can do with scenario composition to help here (stick to shorter line lengths in code for instance)
